apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    apps: nestjs-bullmq
  name: nestjs-bullmq
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nestjs-bullmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-bullmq
    spec:
      containers:
        - name: nestjs-bullmq
          image: "[ACCOUNT_ID].dkr.ecr.ap-southeast-2.amazonaws.com/prometheus-sample-app:nestjs-bullmq"
          env:
            - name: REDIS_HOST
              value: nestjs-bullmq-redis-master # Service name
            - name: REDIS_PORT
              value: '6379'
          ports:
          - containerPort: 3000
          resources: {}
status: {}
