version: '3.1'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: simplerest