version: '3.8'

services:
  tooling:
    build:
      context: tooling
      args:
        TERRAFORM_VERSION: 1.3.6
        TERRAFORM_DOCS_VERSION: 0.16.0
    volumes:
      - { type: bind, source: ., target: /work }
    environment:
      TF_INPUT: ${TFINPUT:-}
      TF_LOG: ${TF_LOG:-INFO}
      TF_LOG_PATH: ${TF_LOG_PATH:-./terraform.log}
      TF_IN_AUTOMATION: ${TF_IN_AUTOMATION:-false}
    working_dir: /work
    privileged: true
