#cert-manager-values.yml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::322839641907:role/externaldns_route53

installCRDs: true

# the securityContext is required, so the pod can access files required to assume the IAM role
# securityContext:
#   enabled: true
#   fsGroup: 1001