# docker exec -it timescaledb-taxidata-timescaledb-1 psql -U timescaledb -W

version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    # volumes:
    #   - tdb_data:/var/lib/postgresql/data

# volumes:
#   tdb_data: {}
