
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample-app-deployment
  namespace: fargate-container-insights
spec:
  selector:
    matchLabels:
      app: prometheus-sample-app
  replicas: 1 # tells deployment to run 5 pods matching the template
  template:
    metadata:
      labels:
        app: prometheus-sample-app
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: prometheus-sample-app
          image: "410239167650.dkr.ecr.ap-southeast-2.amazonaws.com/prometheus-sample-app:latest" 
          # imagePullPolicy: Never
          command:
            - "/bin/main"
          args:
            - "--metric_count=1"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-sample-app-service
  namespace: fargate-container-insights
  labels:
    app: prometheus-sample-app
  annotations:
    scrape: "true"
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: prometheus-sample-app
---
